name: Rodar meu robozinho

on: [push]   # dispara quando você fizer push de código novo

jobs:
  run-robo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Rodar o script
        run: python robo_v10.py
